services:
  dev:
    build: ./dev_proxy
    depends_on:
      - backend
    ports:
      - "8003:80"
  nginx:
    build: ./frontend/
    depends_on:
      - backend
    ports:
      - "8000:80"

  backend:
    build:
      context: ./backend/
    volumes:
      - "./files:/files"
    environment:
      - "DATABASE=postgresql+asyncpg://postgres:postgres@db:5432/pbl"
    #  - "CORS=*"
    # this port should be only used for documentation!
    ports:
      - "8002:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pbl
    volumes:
      - "./db:/var/lib/postgresql/data/"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8001:80"
    depends_on:
      - db
