services:
  backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    volumes:
      - "./files:/files"
    ports:
      - "8000:80"
    environment:
      - "DATABASE=postgresql+asyncpg://postgres:postgres@db:5432/pbl"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pbl

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8001:80"
    depends_on:
      - db
