FROM python:3.10-bullseye
RUN apt update -y && apt install ffmpeg -y

WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
EXPOSE 80
ENV FILE_PATH /files
ENV REDIS_URL "redis://redis:6379"
VOLUME /files


RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt
CMD ["dramatiq", "backend"]
COPY ./backend ./backend
