"""auto_generate id in postgres

Revision ID: 9a1667c55c2e
Revises: 196d4d117216
Create Date: 2022-03-11 21:51:44.445238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1667c55c2e'
down_revision = '196d4d117216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Files', 'user', ['author_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'Files', 'Measurements', ['measurement_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Files', type_='foreignkey')
    op.drop_constraint(None, 'Files', type_='foreignkey')
    # ### end Alembic commands ###
