"""tweak files-measurement relationship

Revision ID: cb729dfd3d2e
Revises: bedbcbc9d2e4
Create Date: 2022-03-12 19:37:27.918706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb729dfd3d2e'
down_revision = 'bedbcbc9d2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
