"""Change location from str to coords

Revision ID: 19d39a85eacb
Revises: cb729dfd3d2e
Create Date: 2022-03-14 15:20:34.677562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d39a85eacb'
down_revision = 'cb729dfd3d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Measurements', sa.Column('location_longitude', sa.Float(), nullable=True))
    op.add_column('Measurements', sa.Column('location_latitude', sa.Float(), nullable=True))
    op.drop_column('Measurements', 'location_string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Measurements', sa.Column('location_string', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('Measurements', 'location_latitude')
    op.drop_column('Measurements', 'location_longitude')
    # ### end Alembic commands ###
