"""Add F_aeq collumn

Revision ID: 51653e6c3c09
Revises: 19d39a85eacb
Create Date: 2022-03-16 19:49:53.189166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51653e6c3c09'
down_revision = '19d39a85eacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Measurements', sa.Column('laeq', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Measurements', 'laeq')
    # ### end Alembic commands ###
