"""Add optimized mime

Revision ID: 9fd1f8185c46
Revises: c9cf9b80f022
Create Date: 2022-04-08 22:43:35.395754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd1f8185c46'
down_revision = 'c9cf9b80f022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Files', sa.Column('optimized_mime', sa.String(length=64), nullable=True))
    op.add_column('Files', sa.Column('optimized_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Files', 'optimized_name')
    op.drop_column('Files', 'optimized_mime')
    # ### end Alembic commands ###
