"""Add weather information

Revision ID: c9cf9b80f022
Revises: 51653e6c3c09
Create Date: 2022-03-28 20:19:32.381529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cf9b80f022'
down_revision = '51653e6c3c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Measurements', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('Measurements', sa.Column('wind_speed', sa.Float(), nullable=True))
    op.add_column('Measurements', sa.Column('pressure', sa.Float(), nullable=True))
    op.add_column('Measurements', sa.Column('humidity', sa.Float(), nullable=True))
    op.add_column('Measurements', sa.Column('weather_status', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Measurements', 'weather_status')
    op.drop_column('Measurements', 'humidity')
    op.drop_column('Measurements', 'pressure')
    op.drop_column('Measurements', 'wind_speed')
    op.drop_column('Measurements', 'temperature')
    # ### end Alembic commands ###
