name: Czy build jest legitny?

on:
  push:
    branches: [ master, cicd ]
  pull_request:
    branches: [ master ]

jobs:
  buildFront:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
      working_directory: ./frontend/editor
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.0.0
      working_directory: ./frontend/editor
      with:
        cmd: lint
    - name: Build Frontend
      run: docker build ./frontend/ --tag pbl-front:$(date +%s)
  buildBack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Backend
      run: docker build ./backend/ --tag pbl-back:$(date +%s)
