name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Frontend
      run: docker build ./frontend/ --tag pbl-front:$(date +%s)
    - name: Build Backend
      run: docker build ./backend/ --tag pbl-back:$(date +%s)
